### PR TITLE
fix: nonScrollEdges being calculated incorrectly

### LINKED ISSUE #33: Item layouting calculates the non-scrolling edges incorrectly
### :bug: Describe

The layout manager should layout the non-layout edges based on the size of the item, not the size of the recycler.

For instance these items are supposed to be 100dp tall:
device-2020-02-15-133907
Yet they are not.

### :snail: Steps to reproduce

1. Load Activity Horizontal.
2. Observe how the items are taller than they should be.

### :butterfly: Expected behavior

Items should be laid out based on their hight.

### :beetle: Other info

N/A

### :bee: Requested assignment

I've already got a fix, this is just documenting the issue.

### PR DESCRIPTION
**Pull request by BeksOmega**
### :clap: Resolves

     
Closes #33
     
### :star2: Description

Changes the LoopingLayoutManager to calculate the non-scrolling edges in the same way that the LinearLayoutManager does.

### :bug: Testing

Tests had to be updated. Specifically ones that were setting the item sizes based on the width of the screen.

Now all tests pass.

### :thought_balloon: Other info

N/A

### CODE REVIEW

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 1]
```diff
@@ -127,12 +115,17 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
...
+                assertNotInLayoutOrScroll(null)
+                field = orientation
+                requestLayout()
                 return
             }
-            assertNotInLayoutOrScroll(null)
-            field = orientation
-            requestLayout()
+            if (!::orientationHelper.isInitialized) {
+
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]: Remove newline

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 2]
```diff
@@ -218,8 +211,6 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
             topLeftIndex = layoutRequest.anchorIndex
             bottomRightIndex = stepIndex(index, -movementDir, state, false)
         }
-
-        layoutRequest.finishProcessing()
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]: For future reference: This was removed because onLayoutChildren can be called multiple times. If the layout request is reset, the layout will be re-laid-out incorrectly on later calls.

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 3]
```diff
@@ -336,6 +328,34 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
...
     }
 
+    /**
+     * Returns a rect populated with the positions of the static edges of the view. I.e. right and
+     * left in horizontal mode, top and bottom in vertical mode.
+     */
+    private fun getNonScrollingEdges(view: View): Rect {
+        val layoutRect = Rect()
+        val isVertical = orientation == VERTICAL
+        // In LTR we align vertical layouts witht the left edge, and in RTL the right edge.
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]:
```suggestion
        // In LTR we align vertical layouts with the left edge, and in RTL the right edge.
```
