### PR TITLE
fix: Padded recyclers not looping correctly.

### LINKED ISSUE #25: Padded Recyclerviews Don't Loop Indices Correctly
* **Device**: Nexus 5 (Emulated)
* **OS Version**: API 29
* **Project Version**: 0.0.2

### :bug: Describe

When the RecyclerView the layout manager is applied to has padding, the indicies are looped incorrectly under certain circumstances.

[Video Link](https://i.imgur.com/z5JgOH5.mp4)

### :snail: Steps to reproduce

1. Edit the layout file to give the RecyclerView 50dp padding.
2. Load the ActivityHorizontal activity. Make sure the layout manager is not reversed.
3. Scroll to see more views at the left.
4. Observe how the view indices are not in the correct order.

### :butterfly: Expected behavior

View indices should be in the correct order.

### :beetle: Other info

N/A

### :bee: Requested assignment

If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by BeksOmega**
### :clap: Resolves

     
Closes #25 
     
### :star2: Description

* Fixed padded recyclers not looping correctly. Yay!
* ListItems now access the height/width directly instead of having it passed.
* Changed some math to use order of operations instead of parens.

### :bug: Testing

Updated all tests to run with a padded recycler view.

All unit tests pass with padded and unpadded recyclers.

### :thought_balloon: Other info

N/A

### CODE REVIEW

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 1]
```diff
@@ -66,6 +66,19 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
             }
             return layoutRect
         }
+
+    /**
+     * The width of the layout - not the recycler.
+     * AKA the width of the recycler, minus the padding on the left and right.
+     */
+    val visibleWidth: Int
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]: Rename to layoutWidth

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 2]
```diff
@@ -66,6 +66,19 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
...
+        get() = width - paddingLeft - paddingRight
+    /**
+     * The height of the layout - not the recycler.
+     * AKA the height of the recycler, minus the padding on the top and bottom.
+     */
+    val visibleHeight: Int
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]: Rename to layoutHeight

File: test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+                location1[1] + view1.paddingTop,
+                location1[0] + view1.width - view1.paddingRight,
+                location1[1] + view1.height - view1.paddingBottom)
+
+        when (position) {
+            Position.LEFT_PADDING -> return rect1.left == rect2.left
+            Position.TOP_PADDING -> return rect1.top == rect2.top
+            Position.RIGHT_PADDING -> return rect1.right == rect2.right
+            Position.BOTTOM_PADDING -> return rect1.bottom == rect2.bottom
+            /*PositionAssertions.Position.COMPLETELY_LEFT_OF -> return location1[0] + view1.width <= location2[0]
```
Comment (BeksOmega) [inline test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt]: Remove commented code.
