### PR TITLE
fix: Fixed null exceptions when recycling.

### LINKED ISSUE #19: Fix recycleViews Null Child References When Flinging
### :key: Problem

The recycleViews function currently loops through children in the order opposite the direction we were just scrolling. I.E. if we were just adding views at the right edge of the recycler, the children will be looped through from right -> left.

The problem is that if we're looping from lower indices to higher indices, recycling a view throws them out of wack, and throws null pointer exceptions.
     
### :hammer: Proposal

The easiest most readable thing to do is probably keep the looping how it currently is. What would change is that instead of recycling views immediately, they would be added to a list. Then once we know what views needed to be removed, we could loop through them from higher -> lower, making sure they get removed without nulls.

### :wrench: Alternative

We could always loop through the child indices from higher -> lower, but there would be different behavior depending on which direction we were just scrolling in.

If were were just scrolling towards lower, the first hidden views we found would get removed.

If we were scrolling towards higher, the last (i.e. following visible) hidden views we found would be removed.

I believe this would get the function down to a single loop, but it may be less readable, and I'm not sure how it would affect updating the topLeftIndex and bottomRightIndex.

### :memo: Other info

I recognised this problem while working on #18, but there's not really relevant information there.

### :bee: Request for assignment

I'm just reporting this. But I wouldn't mind fixing it.

### PR DESCRIPTION
**Pull request by BeksOmega**
### :clap: Resolves

     
Closes #19 
     
### :star2: Description

I decided to go with the first option outlined in the issue. I collected all the indices of views that needed to be recycled. Then after collecting I sorted them from greatest -> least, and recycled them.

This makes sure that we don't get null pointers because of indices shifting.

### :bug: Testing

1. Scrolled to show new views at the top in the vertical test activity.
2. Observed how there were no null pointer exceptions.

I tested the above on develop first (removing the ?: break; child check) and confirmed that there were errors.

All unit tests passed.

### :thought_balloon: Other info

N/A

### CODE REVIEW

File: library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt [hunk 1]
```diff
@@ -526,19 +526,24 @@ class LoopingLayoutManager : LayoutManager, RecyclerView.SmoothScroller.ScrollVe
...
                 distanceFromStart++
             } else if (foundVisibleView){
-                foundHiddenView = true
-                removeAndRecycleViewAt(i, recycler)
+                viewsToRemove.add(i)
             }
         }
 
-        if (!foundHiddenView) {
+        // Removing the views after collecting them and putting them in order from greatest -> makes sure we
```
Comment (BeksOmega) [inline library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt]:
```suggestion
        // Removing the views after collecting them and putting them in order from greatest -> least makes sure we
```
